---
- name: ssh-copy-id
  hosts: "{{ host }}"
  tasks:
    - name: Set authorized key took from file
      authorized_key:
        user: "{{local_user}}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"